import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';import {extraGame,extraMove,triviaV2} from '../src/lib/extra-games';import {filterDates,countdownProgress,conversationQuestions} from '../src/lib/together';
test('Preview quiz answers seal until both submit, drawing ends after five valid guesses',()=>{let g=extraGame('trivia');const answers={};g=extraMove(g,0,{answer:'1'},answers,'');assert.equal(g.state.last,undefined);assert.equal(g.state.round,0);assert.throws(()=>extraMove(g,0,{answer:'0'},answers,''),/already sealed/);g=extraMove(g,1,{answer:'0'},answers,'');assert.deepEqual(g.state.scores,[1,0]);assert.equal(g.state.round,1);assert.equal(triviaV2.length,5);let d=extraGame('draw',0);assert.throws(()=>extraMove(d,0,{guess:'cloud'},{},'cloud'),/artist/);for(let i=0;i<5;i++)d=extraMove(d,1,{guess:'wrong'},{},'cloud');assert.equal(d.state.winner,0);assert.equal(d.state.word,'cloud');assert.equal(conversationQuestions.length,36);assert.equal(new Set(conversationQuestions).size,36);assert.equal(countdownProgress('2026-10-01','2026-10-11','2026-10-06'),.5);assert.equal(countdownProgress('2026-10-01','2026-10-11','2026-10-15'),1);assert.equal(filterDates([{id:'1',kind:'date',body:{title:'Picnic',event:'idea',mood:'cozy',weather:'outdoors'},done:false,created_at:'2026-10-01'}],'cozy','indoors').length,0);});
test('Remaining games protect words, sealed answers, scoring and shared activity writes on the server',async()=>{
 const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create schema realtime;create table realtime.messages(topic text);alter table realtime.messages enable row level security;create function realtime.topic() returns text language sql as $$select current_setting('request.topic',true)$$;create publication supabase_realtime;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(bucket_id text,name text);alter table storage.objects enable row level security;create function storage.foldername(text) returns text[] language sql immutable as $$select string_to_array($1,'/')$$;grant usage on schema auth,public,realtime,storage to authenticated;`);
 for(const p of ['supabase/setup_fresh_project.sql','supabase/migrations/004_block_battle.sql','supabase/migrations/008_together.sql'])await db.exec(await readFile(p,'utf8'));
 const c='06092025-0000-4000-8000-000000000001',a='10000000-0000-4000-8000-000000000001',b='10000000-0000-4000-8000-000000000002',o='10000000-0000-4000-8000-000000000003';
 await db.exec(`insert into auth.users values('${a}'),('${b}'),('${o}');insert into profiles(id,couple_id,slot,name) values('${a}','${c}',0,'One'),('${b}','${c}',1,'Two');set role authenticated;`);
 const as=async(id:string)=>db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await as(a);
 const draw=(await db.query<{id:string;state:Record<string,unknown>}>("select * from new_game('draw')")).rows[0];assert.equal(draw.state.pack,'general-v2');const word=(await db.query<{word:string}>('select drawing_word($1) word',[draw.id])).rows[0].word;assert.ok(word);
 await assert.rejects(db.query('select * from game_secrets'),/permission denied/);await assert.rejects(db.query('select play_game_legacy($1,$2)',[draw.id,{guess:word}]),/permission denied/);
 await as(b);assert.equal((await db.query<{word:null}>('select drawing_word($1) word',[draw.id])).rows[0].word,null);await assert.rejects(db.query('select save_entry($1,$2)', ['stroke',{game:draw.id,color:'#9d304f',points:[[.5,.5]]}]),/artist/);
 for(let i=0;i<5;i++)await db.query('select play_game($1,$2)',[draw.id,{guess:'not-a-word'}]);assert.equal((await db.query<{state:{winner:number;word:string}}> ('select state from games where id=$1',[draw.id])).rows[0].state.winner,0);
 const quiz=(await db.query<{id:string}>("select * from new_game('trivia')")).rows[0];await db.query('select play_game($1,$2)',[quiz.id,{answer:'1',scores:[999,999]}]);await assert.rejects(db.query('select * from game_answers'),/permission denied/);let state=(await db.query<{state:{scores:number[];last?:unknown}}> ('select state from games where id=$1',[quiz.id])).rows[0].state;assert.equal(state.last,undefined);assert.deepEqual(state.scores,[0,0]);
 await as(a);await db.query('select play_game($1,$2)',[quiz.id,{answer:'1'}]);state=(await db.query<{state:{scores:number[];last?:unknown}}> ('select state from games where id=$1',[quiz.id])).rows[0].state;assert.deepEqual(state.scores,[1,1]);
 await db.query('select save_activity($1,$2)', ['date',{title:'Our own plan',event:'idea'}]);await assert.rejects(db.exec("insert into together_activities(couple_id,author,kind,body) values('"+c+"','"+a+"','date','{}')"),/permission denied/);await assert.rejects(db.query('select save_activity($1,$2)',['question',{}]),/Invalid question/);
 const progress=(await db.query<{p:{xp:number;played:number}}> ('select arcade_progress() p')).rows[0].p;assert.equal(progress.played,1);assert.equal(progress.xp,15);
 await as(o);assert.equal((await db.query('select * from together_activities')).rows.length,0);await assert.rejects(db.query('select save_activity($1,$2)',['date',{title:'intrusion'}]),/Sign in/);await assert.rejects(db.query('select play_game($1,$2)',[quiz.id,{answer:'0'}]),/not found|unavailable|invitation|Sign in/i);
 }finally{await db.close();}
});
