import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
test('voice rows/files are private, receipts belong to recipient and stable IDs prevent duplicate messages',async()=>{
 const db=new PGlite(),a='10000000-0000-4000-8000-000000000001',b='10000000-0000-4000-8000-000000000002',c='06092025-0000-4000-8000-000000000001',i='20000000-0000-4000-8000-000000000001',o='10000000-0000-4000-8000-000000000003';
 try{await db.exec(`create role anon;create role authenticated;create schema auth;create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create table couples(id uuid primary key);create table profiles(id uuid primary key,couple_id uuid);create function my_couple() returns uuid language sql stable security definer as $$select couple_id from profiles where id=auth.uid()$$;create table notification_preferences(user_id uuid);create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(bucket_id text,name text,metadata jsonb);alter table storage.objects enable row level security;grant usage on schema auth,storage,public to authenticated,anon;grant select,insert,delete on storage.objects to authenticated;grant select on storage.objects to anon;insert into couples values('${c}');insert into profiles values('${a}','${c}'),('${b}','${c}');`);
 const sql=await readFile('supabase/migrations/016_voice_cassettes.sql','utf8');await db.exec(sql);await db.exec(sql);
 const as=async(id:string)=>{await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);};
 await as(a);await db.query("insert into storage.objects values('voice-notes',$1,'{\"size\":20000}')",[`${c}/${a}/${i}`]);
 const send=()=>db.query('select send_voice($1,$2,$3,$4,$5,$6,$7)',[i,'audio/webm;codecs=opus',2000,Array(64).fill(.2),'Hi','#F8C9D8','heart']);await send();await send();assert.equal((await db.query('select * from voice_messages')).rows.length,1);
 await db.query("select voice_action($1,'listened')",[i]);assert.equal((await db.query<{listened_at:null}>('select listened_at from voice_messages')).rows[0].listened_at,null);
 await as(b);assert.equal((await db.query('select * from storage.objects')).rows.length,1);await db.query("select voice_action($1,'listened')",[i]);assert.ok((await db.query<{listened_at:string|null}>('select listened_at from voice_messages')).rows[0].listened_at);
 await assert.rejects(db.query('delete from storage.objects where name=$1 returning *',[`${c}/${a}/${i}`]).then(r=>{if(r.rows.length===0)throw new Error('not permitted');}));
 await as(o);assert.equal((await db.query('select * from voice_messages')).rows.length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,0);await assert.rejects(db.query("select voice_action($1,'listened')",[i]));await db.exec('set role anon');assert.equal((await db.query('select * from storage.objects')).rows.length,0);await assert.rejects(db.query('select * from voice_messages'));
 }finally{await db.close();}
});
