-- Stage 4. Run once after the existing migrations.
begin;
create table public.wishlists(id uuid primary key default gen_random_uuid(),couple_id uuid not null default public.my_couple() references public.couples,owner_id uuid not null default auth.uid() references public.profiles,type text not null check(type in ('shared','personal','secret','custom')),title text not null check(length(trim(title)) between 1 and 80),cover text not null default 'wish-jar');
create function public.can_read_list(lid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from wishlists where id=lid and couple_id=my_couple() and (type<>'secret' or owner_id=auth.uid())) $$;
create function public.can_edit_list(lid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from wishlists where id=lid and couple_id=my_couple() and (type in ('shared','custom') or owner_id=auth.uid())) $$;
create table public.wishlist_items(id uuid primary key default gen_random_uuid(),list_id uuid not null references public.wishlists on delete cascade,created_by uuid not null default auth.uid() references public.profiles,title text not null check(length(trim(title)) between 1 and 160),note text not null default '' check(length(note)<=2000),url text not null default '' check(url='' or url ~ '^https?://'),price numeric check(price>=0 and price<=1000000000),currency text not null default 'PHP' check(currency ~ '^[A-Z]{3}$'),image_path text,category text not null default '' check(length(category)<=40),priority smallint not null default 1 check(priority between 1 and 3),status text not null default 'wished' check(status in ('wished','planned','done')),planned_date date,done_at timestamptz,position int not null default 0,created_at timestamptz not null default now());
create table public.wishlist_claims(item_id uuid primary key references public.wishlist_items on delete cascade,claimed_by uuid not null default auth.uid() references public.profiles,status text not null check(status in ('getting','bought')));
create function public.valid_wish_image(iid uuid,path text) returns boolean language sql stable security definer set search_path=public as $$ select path is null or path like my_couple()::text||'/'||auth.uid()::text||'/%' or exists(select 1 from wishlist_items i where i.id=iid and i.image_path=path and can_read_list(i.list_id)) $$;
create table public.wishlist_comments(id uuid primary key default gen_random_uuid(),item_id uuid not null references public.wishlist_items on delete cascade,author uuid not null default auth.uid() references public.profiles,body text not null check(length(trim(body)) between 1 and 1000),created_at timestamptz not null default now());
create table public.wishlist_reactions(item_id uuid references public.wishlist_items on delete cascade,user_id uuid default auth.uid() references public.profiles,kind text not null check(kind in ('heart','sparkle','yes')),primary key(item_id,user_id));
create table public.memories(id uuid primary key default gen_random_uuid(),couple_id uuid not null default public.my_couple() references public.couples,author uuid not null default auth.uid() references public.profiles,caption text not null check(length(caption)<=2000),image_path text,swap_day date,created_at timestamptz not null default now(),unique(couple_id,author,swap_day));
create function public.can_read_memory(mid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from memories m where m.id=mid and m.couple_id=my_couple() and (m.swap_day is null or m.author=auth.uid() or (select count(*) from memories b where b.couple_id=m.couple_id and b.swap_day=m.swap_day)=2)) $$;
create table public.memory_reactions(memory_id uuid references public.memories on delete cascade,user_id uuid default auth.uid() references public.profiles,kind text not null check(kind in ('heart','sparkle','yes')),primary key(memory_id,user_id));
create table public.love_notes(id uuid primary key default gen_random_uuid(),couple_id uuid not null default public.my_couple() references public.couples,author uuid not null default auth.uid() references public.profiles,title text not null check(length(trim(title)) between 1 and 120),unlock_at timestamptz,open_when text not null default '' check(open_when in ('','sad','sleepless','missing')),opened_at timestamptz,created_at timestamptz not null default now());
create table public.note_contents(note_id uuid primary key references public.love_notes on delete cascade,body text not null check(length(body)<=10000),media_path text,media_kind text check(media_kind in ('photo','voice')));
create function public.can_read_note(nid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from love_notes n where n.id=nid and n.couple_id=my_couple() and (n.author=auth.uid() or ((n.unlock_at is null or n.unlock_at<=now()) and (n.open_when='' or n.opened_at is not null)))) $$;
create function public.save_love_note(nid uuid,t text,b text,unlock timestamptz default null,occasion text default '',path text default null,media text default null) returns void language plpgsql security definer set search_path=public as $$ begin
 if my_couple() is null then raise exception 'Sign in with a linked account.'; end if;
 if path is not null and path not like my_couple()::text||'/'||auth.uid()::text||'/%' then raise exception 'Invalid private media path'; end if;
 insert into love_notes(id,title,unlock_at,open_when) values(nid,t,unlock,occasion);
 insert into note_contents values(nid,b,path,media);
end $$;
create function public.open_love_note(nid uuid) returns public.note_contents language plpgsql security definer set search_path=public as $$ declare n love_notes; result note_contents; begin
 select * into n from love_notes where id=nid and couple_id=my_couple() for update;
 if not found then raise exception 'This note is unavailable.'; end if;
 if n.author<>auth.uid() and n.unlock_at>now() then raise exception 'This letter is still sealed until its date.'; end if;
 if n.author<>auth.uid() then update love_notes set opened_at=coalesce(opened_at,now()) where id=nid; end if;
 select * into result from note_contents where note_id=nid; return result;
end $$;
alter table wishlists enable row level security;
alter table wishlist_items enable row level security;
alter table wishlist_claims enable row level security;
alter table wishlist_comments enable row level security;
alter table wishlist_reactions enable row level security;
alter table memories enable row level security;
alter table memory_reactions enable row level security;
alter table love_notes enable row level security;
alter table note_contents enable row level security;
create policy list_read on wishlists for select to authenticated using(couple_id=my_couple() and (type<>'secret' or owner_id=auth.uid()));
create policy list_add on wishlists for insert to authenticated with check(couple_id=my_couple() and owner_id=auth.uid());
create policy list_edit on wishlists for update to authenticated using(can_edit_list(id)) with check(couple_id=my_couple());
-- List identity is immutable through the API; title/cover only can be changed.
create policy item_read on wishlist_items for select to authenticated using(can_read_list(list_id));
create policy item_add on wishlist_items for insert to authenticated with check(can_edit_list(list_id) and created_by=auth.uid() and (image_path is null or image_path like my_couple()::text||'/'||auth.uid()::text||'/%'));
create policy item_edit on wishlist_items for update to authenticated using(can_edit_list(list_id)) with check(can_edit_list(list_id) and valid_wish_image(id,image_path));
create policy item_delete on wishlist_items for delete to authenticated using(can_edit_list(list_id));
create policy claim_read on wishlist_claims for select to authenticated using(claimed_by=auth.uid() and exists(select 1 from wishlist_items i join wishlists l on l.id=i.list_id where i.id=item_id and l.couple_id=my_couple() and l.type='personal' and l.owner_id<>auth.uid()));
create policy claim_write on wishlist_claims for insert to authenticated with check(claimed_by=auth.uid() and exists(select 1 from wishlist_items i join wishlists l on l.id=i.list_id where i.id=item_id and l.couple_id=my_couple() and l.type='personal' and l.owner_id<>auth.uid()));
create policy claim_edit on wishlist_claims for update to authenticated using(claimed_by=auth.uid()) with check(claimed_by=auth.uid() and exists(select 1 from wishlist_items i join wishlists l on l.id=i.list_id where i.id=item_id and l.couple_id=my_couple() and l.type='personal' and l.owner_id<>auth.uid()));
create policy claim_delete on wishlist_claims for delete to authenticated using(claimed_by=auth.uid());
create policy comment_read on wishlist_comments for select to authenticated using(exists(select 1 from wishlist_items i where i.id=item_id and can_read_list(i.list_id)));
create policy comment_add on wishlist_comments for insert to authenticated with check(author=auth.uid() and exists(select 1 from wishlist_items i where i.id=item_id and can_read_list(i.list_id)));
create policy reaction_read on wishlist_reactions for select to authenticated using(exists(select 1 from wishlist_items i where i.id=item_id and can_read_list(i.list_id)));
create policy reaction_add on wishlist_reactions for insert to authenticated with check(user_id=auth.uid() and exists(select 1 from wishlist_items i where i.id=item_id and can_read_list(i.list_id)));
create policy reaction_edit on wishlist_reactions for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid() and exists(select 1 from wishlist_items i where i.id=item_id and can_read_list(i.list_id)));
create policy memory_read on memories for select to authenticated using(can_read_memory(id));
create policy memory_add on memories for insert to authenticated with check(couple_id=my_couple() and author=auth.uid() and (swap_day is null or swap_day=(now() at time zone 'Asia/Manila')::date) and (image_path is null or image_path like my_couple()::text||'/'||auth.uid()::text||'/%'));
create policy memory_reaction_read on memory_reactions for select to authenticated using(can_read_memory(memory_id));
create policy memory_reaction_add on memory_reactions for insert to authenticated with check(user_id=auth.uid() and can_read_memory(memory_id));
create policy memory_reaction_edit on memory_reactions for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid() and can_read_memory(memory_id));
create policy note_read on love_notes for select to authenticated using(couple_id=my_couple());
create policy content_read on note_contents for select to authenticated using(can_read_note(note_id));
grant select,insert on wishlists,wishlist_items,wishlist_comments,memories,wishlist_reactions,memory_reactions to authenticated;
grant update(title,cover) on wishlists to authenticated;
grant update(title,note,url,price,currency,image_path,category,priority,status,planned_date,done_at,position),delete on wishlist_items to authenticated;
grant select,insert,delete on wishlist_claims to authenticated;
grant update on wishlist_claims,wishlist_reactions,memory_reactions to authenticated;
create function public.received_gift(iid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from wishlist_items i join wishlists l on l.id=i.list_id join wishlist_claims c on c.item_id=i.id where i.id=iid and l.couple_id=my_couple() and l.owner_id=auth.uid() and l.type='personal' and i.status='done') $$;
revoke execute on function received_gift(uuid) from public,anon;
grant execute on function received_gift(uuid) to authenticated;
revoke execute on function valid_wish_image(uuid,text) from public,anon;
grant execute on function valid_wish_image(uuid,text) to authenticated;
grant select on love_notes,note_contents to authenticated;
revoke execute on function can_read_list(uuid),can_edit_list(uuid),can_read_memory(uuid),can_read_note(uuid),save_love_note(uuid,text,text,timestamptz,text,text,text),open_love_note(uuid) from public,anon;
grant execute on function can_read_list(uuid),can_edit_list(uuid),can_read_memory(uuid),can_read_note(uuid),save_love_note(uuid,text,text,timestamptz,text,text,text),open_love_note(uuid) to authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('keepsakes','keepsakes',false,10000000,array['image/webp','audio/webm','audio/mp4','audio/ogg']) on conflict(id) do nothing;
create policy keepsake_upload on storage.objects for insert to authenticated with check(bucket_id='keepsakes' and (storage.foldername(name))[1]=my_couple()::text and (storage.foldername(name))[2]=auth.uid()::text);
create policy keepsake_read on storage.objects for select to authenticated using(bucket_id='keepsakes' and (storage.foldername(name))[1]=my_couple()::text and ((storage.foldername(name))[2]=auth.uid()::text or exists(select 1 from wishlist_items i where i.image_path=name and can_read_list(i.list_id)) or exists(select 1 from memories m where m.image_path=name and can_read_memory(m.id)) or exists(select 1 from note_contents n where n.media_path=name and can_read_note(n.note_id))));
-- Claims/secret ideas are deliberately absent from Realtime publications and broadcasts.
-- Postgres sends only rows the subscribed account's SELECT policies permit.
create policy keepsake_live_read on realtime.messages for select to authenticated using(realtime.topic()='keepsakes:'||my_couple()::text);
alter publication supabase_realtime add table public.wishlists,public.wishlist_items,public.wishlist_comments,public.memories,public.love_notes;
notify pgrst,'reload schema';
commit;
